Questions = [
    "You find it difficult to introduce yourself to other people.",
    "You often get so lost in thoughts that you ignore or forget your surroundings.",
    "You try to respond to your e-mails as soon as possible and cannot stand a messy inbox.",
    "You find it easy to stay relaxed even when there is some pressure.",
    "You do not usually initiate conversations.",
    "You rarely do something just out of sheer curiosity.",
    "You feel superior to other people.",
    "Being organized is more important to you than being adaptable.",
    "You are usually highly motivated and energetic.",
    "Winning a debate matters less to you than making sure no one gets upset.",
    "You often feel as if you have to justify yourself to other people.",
    "Your home and work environments are quite tidy.",
    "You do not mind being at the center of attention.",
    "You consider yourself more practical than creative.",
    "People can rarely upset you.",
    "Your travel plans are usually well thought out.",
    "It is often difficult for you to relate to other people’s feelings.",
    "Your mood can change very quickly.",
    "In a discussion, truth should be more important than people’s sensitivities.",
    "You rarely worry about how your actions affect other people.",
    "Your work style is closer to random energy spikes than to a methodical and organized approach.",
    "You are often envious of others.",
    "An interesting book or a video game is often better than a social event.",
    "Being able to develop a plan and stick to it is the most important part of every project.",
    "You rarely get carried away by fantasies and ideas.",
    "You often find yourself lost in thought when you are walking in nature.",
    "If someone does not respond to your e-mail quickly, you start worrying if you said something wrong.",
    "As a parent, you would rather see your child grow up kind than smart.",
    "You do not let other people influence your actions.",
    "When you sleep, your dreams tend to focus on the real world and its events.",
    "It does not take you much time to start getting involved in social activities at your new workplace.",
    "You are more of a natural improviser than a careful planner.",
    "Your emotions control you more than you control them.",
    "You enjoy going to social events that involve dress-up or role-play activities.",
    "You often spend time exploring unrealistic and impractical yet intriguing ideas.",
    "You would rather improvise than spend time coming up with a detailed plan.",
    "You are a relatively reserved and quiet person.",
    "If you had a business, you would find it very difficult to fire loyal but underperforming employees.",
    "You often contemplate the reasons for human existence.",
    "Logic is usually more important than heart when it comes to making important decisions.",
    "Keeping your options open is more important than having a to-do list.",
    "If your friend is sad about something, you are more likely to offer emotional support than suggest ways to deal with the problem.",
    "You rarely feel insecure.",
    "You have no difficulties coming up with a personal timetable and sticking to it.",
    "Being right is more important than being cooperative when it comes to teamwork.",
    "You think that everyone’s views should be respected regardless of whether they are supported by facts or not.",
    "You feel more energetic after spending time with a group of people.",
    "You frequently misplace your things.",
    "You see yourself as very emotionally stable.",
    "Your mind is always buzzing with unexplored ideas and plans.",
    "You would not call yourself a dreamer.",
    "You usually find it difficult to relax when talking in front of many people.",
    "Generally speaking, you rely more on your experience than your imagination.",
    "You worry too much about what other people think.",
    "If the room is full, you stay closer to the walls, avoiding the center.",
    "You have a tendency to procrastinate until there is not enough time to do everything.",
    "You feel very anxious in stressful situations.",
    "You believe that it is more rewarding to be liked by others than to be powerful.",
    "You have always been interested in unconventional and ambiguous things, e.g. in books, art, or movies.",
    "You often take initiative in social situations."
]